AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Security and Encryption Compliance

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref RouteTable

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Custom SG with no default rules"
      VpcId: !Ref VPC
      SecurityGroupIngress: []
      SecurityGroupEgress: []

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      ImageId: ami-0c55b159cbfafe1f0 # Replace with valid AMI ID
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            Encrypted: true
      MetadataOptions:
        HttpTokens: required
        HttpEndpoint: enabled

  SnapshotPolicy:
    Type: AWS::DLM::LifecyclePolicy
    Properties:
      Description: "Snapshot policy with encryption"
      ExecutionRoleArn: arn:aws:iam::123456789012:role/AWSDataLifecycleManagerDefaultRole
      State: ENABLED
      PolicyDetails:
        - ResourceTypes: ["VOLUME"]
          TargetTags:
            - Key: Backup
              Value: true
          Schedules:
            - Name: DailySnapshots
              CreateRule:
                Interval: 24
                IntervalUnit: HOURS
              RetainRule:
                Count: 7
              CopyTags: true
              TagsToAdd:
                - Key: Encrypted
                  Value: true
